Проект 10-ого спринта. Версия 1
Armmacham/java-filmorate pull request #8
Opened 2023-01-17 18:10 UTC by Armmacham

2023-01-20 21:24 UTC, NikolaiDem requested changes

2023-01-20 21:24 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        if (friends == null) {
Конструкция 
if (friends == null) {
            friends = new HashSet<>();
        }
трижды повторяется в коде. Лучше вынести в отдельный метод.

2023-01-20 21:24 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validateReleaseDate(film, "Создан фильм");
Проверка даты ведь сделана уже с помощью аннотации CorrectReleaseDate.

2023-01-20 21:24 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .filter(getUserById(secondUserId).getAllFriendsId()::contains)
Лучше вынести друзей в отдельную переменную:
        Set<Integer> otherFriendsId = getUserById(secondUserId).getAllFriendsId();

2023-01-20 21:24 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
В репозитории лучше оставить только методы добавления, удаления и модификации объектов. А методы с бизнес-логикой перенести в сервис.
Аналогично для UserStorage.

2023-01-21 14:24 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    @ExceptionHandler
Объединил методы handleFilmNotFound, handleUserNotFound, handleValidationException в один метод alreadyExistsHandler. 
Методы handleFilmNotFound и handleUserNotFound notFoundHandler.

2023-01-21 14:39 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getTopRatedFilms(@RequestParam(value = "count", defaultValue = "10", required = false) Integer count) {
Прочитал в документации Оракал Annotation Interface RequestParam про defaultValue - удалил required = false.

2023-01-21 15:00 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/UserAlreadyExistsException.java
> +public class UserAlreadyExistsException extends RuntimeException {
Классы UsersLikeNotFoundException, FilmNotFoundException, UserNotFoundException объединил в класс EntityNotFoundException. 
Классы UserAlreadyExistsException и FilmAlreadyExistsException объединил в класс EntityAlreadyExistsException. 
Провёл соответствующий рефакторинг в классе ErrorHandler.

2023-01-21 15:07 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (likesCount == null) {
likesCount не должен быть null, так как прописано "this.likesCount = Objects.requireNonNullElseGet(likesCount, HashSet::new)".
Забыл удалить проверку в методе addLike после изменения this.likesCount.
Удалил if (likesCount == null).

2023-01-21 15:18 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        if (friends == null) {
Добавил метод по проверке friends на null - checkFriendsList().

2023-01-21 15:40 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validateReleaseDate(film, "Создан фильм");
Да, точно - удалил validateReleaseDate() из методов addFilm() и updateFilm(). Сам метод оставил - он используется в тестах.

2023-01-21 15:50 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .filter(getUserById(secondUserId).getAllFriendsId()::contains)
Вынес друзей второго пользователя в отдельную переменную - "otherFriendsId ".

2023-01-21 17:07 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
Перенёс методы removeLike(), addLike и getTopRatedFilms() в FilmService.
Перенёс метод getUserFriends() в UserService.
Провёл соответствующий рефакторинг.

2023-01-22 23:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public Set checkFriendsList() {
Set<Integer>

2023-01-22 23:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validateReleaseDate(film, "Создан фильм");
Так как в рабочем коде метод не используется, то лучше удалить.

2023-01-22 23:52 UTC, NikolaiDem approved these changes

2023-02-14 17:43 UTC, merged