Add database
Armmacham/java-filmorate pull request #9
Opened 2023-02-22 15:26 UTC by Armmacham

2023-02-22 18:46 UTC, z8q requested changes
Привет!
Комментарии оставил.

2023-02-22 18:46 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        if (user.getFriends() != null) {
Тут в одном методе идет три обращения к базе:
update, 
addFriend(количество обращений зависит от количества друзей), 
getUserById

Возможно было бы правильно допустить, что новый User в системе сразу с друзьями появиться не может.
Лучше было бы разделить эти действия.

И тут дао слой, 
то есть было бы правильно по возможности упростить обращения. А логику и очередность вызовов методов сделать в сервисах

2023-02-22 18:46 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          User user = userStorage.getUserById(userId);
Тут тоже получение друзей идет через несколько запросов к базе,  хотя можно было бы ограничиться одним. Sql запрос был бы посложнее

2023-02-22 18:46 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List otherFriendsId = getUserById(secondUserId).getAllFriendsId();
List нехорошо без типа оставлять

2023-02-22 18:46 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private int increment = 0;
Поле похоже не используется

2023-02-22 18:46 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        if (film.getLikesCount() != null) {
В UserDb добавил коммент про друзей,  тут тоже можно еще подумать, стоит ли добавлять новый фильм сразу с лайками.

2023-02-22 19:34 UTC, Armmacham commented on src/main/resources/schema.sql
> +    ReleaseDate date         NOT NULL,
Переименовал столбцы согласно snack_case.

2023-02-22 19:45 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List otherFriendsId = getUserById(secondUserId).getAllFriendsId();
Добавил тип элемента List.

2023-02-22 19:46 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private int increment = 0;
Удалил increment.

2023-02-22 21:05 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    public boolean deleteUser(User user) {
Сейчас реализовал удаление фильмов и пользователь через объекты, а не через id, как обычно( 
Если это не принципиально, было бы удобнее оставить так..

2023-02-24 04:12 UTC, z8q requested changes

2023-02-24 04:12 UTC, z8q commented on src/main/resources/schema.sql
> +ALTER TABLE Friendship
Про constraint-ы такого вида, как в строках 78 и 82,
Мы же можем выставить REFERENCES прямо при создании таблицы: references Users,
почему решил сделать так?

2023-02-24 12:29 UTC, Armmacham commented on src/main/resources/schema.sql
> +ALTER TABLE Friendship
Можно было и так сделать, но таким образом сама табличка не пересыщается информацией.

2023-02-24 12:32 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Integer> likesCount = new ArrayList<>();
Переделал под set (хоть проверка была для повторов). Сейчас перенёс в schemа.sql - через UNIQUE INDEХ проверяю.

2023-02-24 12:36 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +            String setNewGenres = "insert into GENRELINE (FILM_ID, GENRE_ID) values (?, ?) ON CONFLICT DO NOTHING;";
Добавил аннотации @NotNull и @Min(value = 1) для id у жанра. Теперь, если не указать id то фильм не будет добавлен в базу.

2023-02-24 12:40 UTC, Armmacham commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          User user = userStorage.getUserById(userId);
Заменил возвращаемый тип List у метода getUsersFrinds на User. И возвращаю друзей пользователя запросом sql. В методе makeUser тоже использую этот метод и stream-ом достаю id друзей.

2023-02-24 12:42 UTC, Armmacham commented on src/main/resources/schema.sql
> +    CONSTRAINT uc_User_Email UNIQUE (email)
Добавил в schema.sql проверку уникальности логина через UNIQUE INDEX.

2023-02-25 04:17 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +            String setNewGenres = "insert into GENRELINE (FILM_ID, GENRE_ID) values (?, ?) ON CONFLICT DO NOTHING;";
Можно еще подумать, будешь ли допускать сохранение фильма без определенных данных.
Например сейчас фильм успешно сохраняется, если не передаем жанры.
Если не заполняем mpa, то выходит ошибка, а фильм при этом сохраняется.
Не заполненные duration и rating сохраняют со значением 0. Для рейтинга по-идее допустимо, для продолжительности не уверен

2023-02-25 04:23 UTC, z8q approved these changes

2023-02-25 04:23 UTC, z8q commented on src/main/resources/data.sql
> +DELETE FROM LIKES;
Тут возможно дублируется информация.
Что два раза делаем MERGE для рейтинга и жанров

2023-03-07 21:46 UTC, merged